### ISSUE TITLE
Adding "update_environment" after creating the applciation

### ISSUE THREAD

**Issue by joshdvir** [josmo/drone-elastic-beanstalk#5]
Hi,

In order to provide a real CD can you guys please add flag that states whether to also update the environment with the new version or not.

Great work!!!

Thanks

**Comment by tboerger** [comment]
Got to check the options of the go aws sdk, but if i find this option we can offer that for sure.

**Comment by joshdvir** [comment]
@tboerger have a look - http://docs.aws.amazon.com/sdk-for-go/api/service/elasticbeanstalk.html#type-UpdateEnvironmentInput

Thanks man that would be awesome

**Comment by tboerger** [comment]
I don't really know what happens on the AWS side with this, so you need `UpdateEnvironmentInput` and not `CreateEnvironmentInput`?

**Comment by dcoxall** [comment]
Is this closed now?

**Comment by tboerger** [comment]
:+1:
